### ISSUE TITLE
Keep pom.xml updated with the dependencies in UniSeats.iml

### ISSUE THREAD

**Issue by vincenzorusso3** [vincenzorusso12/UniSeats#3]
Otherwise Travis-CI will not work.

**Comment by vincenzorusso12** [comment]
Here are the dependencies

<orderEntry type="library" name="mysql-connector-java-8.0.12" level="project" />
    <orderEntry type="library" name="mockito-core-3.7.7" level="project" />
    <orderEntry type="library" name="spring-jcl-5.3.3" level="project" />
    <orderEntry type="library" name="spring-core-5.3.3" level="project" />
    <orderEntry type="library" name="spring-test-5.3.3" level="project" />
    <orderEntry type="library" name="Maven: org.springframework:spring-core:5.3.3" level="project" />
    <orderEntry type="library" name="Maven: org.springframework:spring-jcl:5.3.3" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.springframework:spring-test:5.3.3" level="project" />
    <orderEntry type="library" name="Maven: mysql:mysql-connector-java:8.0.12" level="project" />
    <orderEntry type="library" name="Maven: com.google.protobuf:protobuf-java:2.6.0" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.mockito:mockito-core:3.7.7" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: net.bytebuddy:byte-buddy:1.10.19" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: net.bytebuddy:byte-buddy-agent:1.10.19" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.objenesis:objenesis:3.1" level="project" />
    <orderEntry type="library" scope="PROVIDED" name="Maven: javax.servlet:javax.servlet-api:4.0.1" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.junit.jupiter:junit-jupiter-api:5.7.0" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.apiguardian:apiguardian-api:1.1.0" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.opentest4j:opentest4j:1.2.0" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.junit.platform:junit-platform-commons:1.7.0" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.junit.jupiter:junit-jupiter-engine:5.7.0" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.junit.platform:junit-platform-engine:1.7.0" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: junit:junit:4.12" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.hamcrest:hamcrest-core:1.3" level="project" />
    <orderEntry type="library" name="Maven: org.springframework:spring-core:5.3.3" level="project" />
    <orderEntry type="library" name="Maven: org.springframework:spring-jcl:5.3.3" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.springframework:spring-test:5.3.3" level="project" />
    <orderEntry type="library" name="Maven: mysql:mysql-connector-java:8.0.12" level="project" />
    <orderEntry type="library" name="Maven: com.google.protobuf:protobuf-java:2.6.0" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.mockito:mockito-core:3.7.7" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: net.bytebuddy:byte-buddy:1.10.19" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: net.bytebuddy:byte-buddy-agent:1.10.19" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.objenesis:objenesis:3.1" level="project" />

**Comment by vincenzorusso12** [comment]
<orderEntry type="library" name="mysql-connector-java-8.0.12" level="project" />
    <orderEntry type="library" name="mockito-core-3.7.7" level="project" />
    <orderEntry type="library" name="spring-jcl-5.3.3" level="project" />
    <orderEntry type="library" name="spring-core-5.3.3" level="project" />
    <orderEntry type="library" name="spring-test-5.3.3" level="project" />
    <orderEntry type="library" name="Maven: org.springframework:spring-core:5.3.3" level="project" />
    <orderEntry type="library" name="Maven: org.springframework:spring-jcl:5.3.3" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.springframework:spring-test:5.3.3" level="project" />
    <orderEntry type="library" name="Maven: mysql:mysql-connector-java:8.0.12" level="project" />
    <orderEntry type="library" name="Maven: com.google.protobuf:protobuf-java:2.6.0" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.mockito:mockito-core:3.7.7" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: net.bytebuddy:byte-buddy:1.10.19" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: net.bytebuddy:byte-buddy-agent:1.10.19" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.objenesis:objenesis:3.1" level="project" />
    <orderEntry type="library" scope="PROVIDED" name="Maven: javax.servlet:javax.servlet-api:4.0.1" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.junit.jupiter:junit-jupiter-api:5.7.0" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.apiguardian:apiguardian-api:1.1.0" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.opentest4j:opentest4j:1.2.0" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.junit.platform:junit-platform-commons:1.7.0" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.junit.jupiter:junit-jupiter-engine:5.7.0" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.junit.platform:junit-platform-engine:1.7.0" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: junit:junit:4.12" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.hamcrest:hamcrest-core:1.3" level="project" />
    <orderEntry type="library" name="Maven: org.springframework:spring-core:5.3.3" level="project" />
    <orderEntry type="library" name="Maven: org.springframework:spring-jcl:5.3.3" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.springframework:spring-test:5.3.3" level="project" />
    <orderEntry type="library" name="Maven: mysql:mysql-connector-java:8.0.12" level="project" />
    <orderEntry type="library" name="Maven: com.google.protobuf:protobuf-java:2.6.0" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.mockito:mockito-core:3.7.7" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: net.bytebuddy:byte-buddy:1.10.19" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: net.bytebuddy:byte-buddy-agent:1.10.19" level="project" />
    <orderEntry type="library" scope="TEST" name="Maven: org.objenesis:objenesis:3.1" level="project" />

**Comment by vincenzorusso12** [comment]
[dependencies.txt](https://github.com/vincenzorusso12/UniSeats/files/5844083/dependencies.txt)
Here are the dependencies from the .iml file
